image: node:14.17.0-alpine3.12

deploy_production:
  stage: deploy
  only:
    - main
  script:
    - cd functions
    - npm install
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN cloud-nest
    - firebase deploy --only functions --token $FIREBASE_TOKEN
