image: node:14.17.0-alpine3.12

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths: 
      - build/

deploy_hosting:
  stage: deploy
  environment: Production
  only:
    - master
  script:
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN boginooo-nest
    - firebase deploy --only hosting --token $FIREBASE_TOKEN

deploy_functions:
  stage: deploy
  only:
    - master
  script:
    - cd functions
    - npm install
    - npm install -g firebase-tools
    - firebase use --token $FIREBASE_TOKEN
    - firebase deploy --only functions --token $FIREBASE_TOKEN
